### ISSUE TITLE
MacBook M1: crash in QEMU

### ISSUE THREAD

**Issue by owalmirneto** [heidiks/rabbitmq-delayed-message-exchange#4]
Hi @heidiks!

I have a problem with chip arm for your latest version`3.9.7-management`.

When I run `docker-compose up` I get the follow error:

```
rabbitmq         | qemu: uncaught target signal 11 (Segmentation fault) - core dumped

...

rabbitmq         | BOOT FAILED
rabbitmq         | ===========
rabbitmq         | Exception during startup:
rabbitmq         |
rabbitmq         | error:badarg
rabbitmq         |
rabbitmq         |     erlang:get_module_info/2

...

rabbitmq exited with code 0
```

I created a gist with full log 👉🏼 https://gist.github.com/owalmirneto/eb18680348db95a6504b11735ef01a0e.

Do you know how I can solve this?

Thanks for you help =)

PS: I tried on MacBook Air with chip M1

**Comment by owalmirneto** [comment]
@heidiks I believe that problem is related with PR #2, because it changed the way the image builds. That makes sense?

**Comment by heidiks** [comment]
Hey @owalmirneto, I'm just tested, and it worked for me, could you please paste your yaml file?

My file:
```
version: '3.3'

services:
  rabbit:
    image: heidiks/rabbitmq-delayed-message-exchange:latest
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
```

I tried on a Mac with Intel chip.

**Comment by owalmirneto** [comment]
Sure man. my `docker-compose.yml` is:

```yaml
version: '3.7'

services:
  postgresdb:
    …
  elasticsearch:
    …
  rabbitmq:
    container_name: rabbitmq
    image: heidiks/rabbitmq-delayed-message-exchange:3.9.7-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
```

But I tried with `image: heidiks/rabbitmq-delayed-message-exchange:latest`, like yours, with `image: heidiks/rabbitmq-delayed-message-exchange:3.9.0-management` and dont works to me =/

Just work with `image: heidiks/rabbitmq-delayed-message-exchange:3.8.9-management`
